services:
  test-db:
    extends:
      file: docker-compose.base.yml
      service: db-base
    profiles:
      - test
    ports:
      - "127.0.0.1:5432:5432"
  
  db:
    extends:
      file: docker-compose.base.yml
      service: db-base
    container_name: quotient_database
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    container_name: quotient_server
    image: quotient_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quotient_network
    volumes:
      - ./submissions:/app/submissions
      - ./config:/app/config
      - ./engine:/app/engine
      - ./static:/app/static

  test-redis:
    extends:
      file: docker-compose.base.yml
      service: redis-base
    profiles:
      - test
    ports:
      # Don't conflict with actual redis instance
      - "127.0.0.1:6380:6379"

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis-base
    restart: always
    container_name: quotient_redis
    ports:
      - "127.0.0.1:6379:6379"

  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    deploy:
      mode: replicated
      replicas: 5 # Adjust based on server resources
    restart: always
    privileged: false # disable unless a runner needs priv access (e.g. wireguard)
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - quotient_network
    volumes:
      - ./submissions:/app/submissions
      - ./custom-checks:/app/checks
      - ./config/scoredfiles:/app/config/scoredfiles
    tmpfs:
      - /tmp:size=32m

  divisor:
    build:
      context: divisor/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    network_mode: host # Use host networking for divisor
    depends_on:
      redis:
        condition: service_healthy
    privileged: true # Needed to manage networks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Needed to read runner names

networks:
  quotient_network:
    driver: bridge

volumes:
  db_data:
