package api

import (
	"bufio"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/dbaseqp/Quotient/engine/config"

	"github.com/go-ldap/ldap/v3"
	"github.com/gorilla/securecookie"
)

var (
	hashKey       []byte
	blockKey      []byte
	CookieEncoder *securecookie.SecureCookie
)

const COOKIENAME = "quotient"

// cookieSecure returns whether cookies should use the Secure flag (HTTPS only)
func cookieSecure() bool {
	// If OIDC is enabled and using HTTPS callback, enforce secure cookies
	if conf.OIDCSettings.OIDCEnabled && strings.HasPrefix(conf.OIDCSettings.OIDCRedirectURL, "https://") {
		return true
	}
	// Otherwise, use secure cookies only if SSL is configured
	return conf.SslSettings != (config.SslConfig{})
}

func init() {
	if _, err := os.Stat("config/COOKIEKEY"); err != nil {
		// Ensure config directory exists
		if err := os.MkdirAll("config", 0750); err != nil { // #nosec G301 -- config dir needs group read for deployment
			log.Fatalln(err)
		}
		w, err := os.Create("config/COOKIEKEY")
		if err != nil {
			log.Fatalln(err)
		}
		// nolint:errcheck
		defer w.Close()

		hashKey = securecookie.GenerateRandomKey(64)
		blockKey = securecookie.GenerateRandomKey(32)
		_, _ = fmt.Fprintln(w, "# AUTOMATICALLY GENERATED BY INIT DO NOT TOUCH")
		_, _ = fmt.Fprintf(w, "hashKey=%s\n", base64.StdEncoding.EncodeToString(hashKey))
		_, _ = fmt.Fprintf(w, "blockKey=%s\n", base64.StdEncoding.EncodeToString(blockKey))
	} else {
		f, err := os.Open("config/COOKIEKEY")
		if err != nil {
			log.Fatalln(err)
		}
		// nolint:errcheck
		defer f.Close()

		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			line := scanner.Text()
			if strings.Contains(line, "hashKey=") {
				decoded, err := base64.StdEncoding.DecodeString(strings.ReplaceAll(line, "hashKey=", ""))
				if err != nil {
					log.Fatalln(err)
				}
				hashKey = decoded
			} else if strings.Contains(line, "blockKey=") {
				decoded, err := base64.StdEncoding.DecodeString(strings.ReplaceAll(line, "blockKey=", ""))
				if err != nil {
					log.Fatalln(err)
				}
				blockKey = decoded
			}
		}
	}
	CookieEncoder = securecookie.New(hashKey, blockKey)
}

func Login(w http.ResponseWriter, r *http.Request) {
	type Form struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}

	var form Form

	decoder := json.NewDecoder(r.Body)
	err := decoder.Decode(&form)
	if err != nil {
		WriteJSON(w, http.StatusBadRequest, map[string]any{"error": "Invalid request body"})
		slog.Error(err.Error())
		return
	}

	// check credentials
	auth, err := auth(form.Username, form.Password)
	if err != nil {
		WriteJSON(w, http.StatusUnauthorized, map[string]any{"error": "Incorrect username/password"})
		slog.Info("Failed logon", "username", form.Username)
		return
	}

	cookie, err := CookieEncoder.Encode(COOKIENAME, auth)
	if err != nil {
		WriteJSON(w, http.StatusInternalServerError, map[string]any{"error": "Authentication error"})
		slog.Error(err.Error())
		return
	}

	http.SetCookie(w, &http.Cookie{
		Name:     COOKIENAME,
		Value:    cookie,
		MaxAge:   int((time.Hour * 24).Seconds()),
		HttpOnly: true,
		Secure:   cookieSecure(),
		SameSite: http.SameSiteLaxMode,
		Path:     "/",
	})

	slog.Info("Successful login", "username", form.Username)
}

func Logout(w http.ResponseWriter, r *http.Request) {
	http.SetCookie(w, &http.Cookie{
		Name:     COOKIENAME,
		Value:    "",
		MaxAge:   0,
		HttpOnly: true,
		Secure:   cookieSecure(),
		SameSite: http.SameSiteLaxMode,
		Path:     "/",
	})
	slog.Info("Successful logout", "username", r.Context().Value("username"))
}

// Authenticate resolves the caller from their session cookie. Reports false
// when the request carries no usable session, or when the identity cannot be
// resolved, in which case it also clears the cookie. Refreshes the cookie on
// success.
func Authenticate(w http.ResponseWriter, r *http.Request) (Identity, bool) {
	token, err := r.Cookie(COOKIENAME)
	if err != nil {
		if err != http.ErrNoCookie {
			slog.Error(err.Error())
		}
		return Identity{}, false
	}

	var value map[string]any
	if err := CookieEncoder.Decode(COOKIENAME, token.Value, &value); err != nil {
		slog.Error(err.Error())
		return Identity{}, false
	}

	username, ok := value["username"].(string)
	if !ok || username == "" {
		slog.Error("session cookie carries no username")
		return Identity{}, false
	}

	// Extract auth source (default to "local" for backward compatibility)
	authSource := "local"
	if source, ok := value["authSource"].(string); ok {
		authSource = source
	}

	id, err := resolveIdentity(username, authSource)
	if err != nil {
		slog.Error(err.Error())
		http.SetCookie(w, &http.Cookie{
			Name:     COOKIENAME,
			Value:    "",
			MaxAge:   -1,
			HttpOnly: true,
			Secure:   cookieSecure(),
			SameSite: http.SameSiteLaxMode,
			Path:     "/",
		})
		return Identity{}, false
	}

	// cookie refresh while still have value
	http.SetCookie(w, &http.Cookie{
		Name:     COOKIENAME,
		Value:    token.Value,
		MaxAge:   int((time.Hour * 24).Seconds()),
		HttpOnly: true,
		Secure:   cookieSecure(),
		SameSite: http.SameSiteLaxMode,
		Path:     "/",
	})

	return id, true
}

func auth(username string, password string) (map[string]any, error) {
	for _, admin := range conf.Admin {
		if username == admin.Name && password == admin.Pw {
			return map[string]any{"username": username, "authSource": "local"}, nil
		}
	}
	for _, team := range conf.Team {
		if username == team.Name && password == team.Pw {
			return map[string]any{"username": username, "authSource": "local"}, nil
		}
	}
	for _, red := range conf.Red {
		if username == red.Name && password == red.Pw {
			return map[string]any{"username": username, "authSource": "local"}, nil
		}
	}
	for _, inject := range conf.Inject {
		if username == inject.Name && password == inject.Pw {
			return map[string]any{"username": username, "authSource": "local"}, nil
		}
	}

	// auth from other sources
	// if ldap configs are present, try to auth against ldap
	if conf.LdapSettings != (config.LdapAuthConfig{}) {
		conn, err := ldap.DialURL(conf.LdapSettings.LdapConnectUrl)
		if err != nil {
			return nil, err
		}
		// nolint:errcheck
		defer conn.Close()

		// bind using the given username and password and searchbase from config
		err = conn.Bind(conf.LdapSettings.LdapBindDn, conf.LdapSettings.LdapBindPassword)
		if err != nil {
			return nil, err
		}

		searchRequest := ldap.NewSearchRequest(
			conf.LdapSettings.LdapSearchBaseDn,
			ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
			fmt.Sprintf("(&(objectClass=person)(sAMAccountName=%s))", ldap.EscapeFilter(username)),
			[]string{"dn"},
			nil,
		)

		sr, err := conn.Search(searchRequest)
		if err != nil {
			return nil, err
		}

		if len(sr.Entries) != 1 {
			return nil, errors.New("user does not exist or too many entries returned")
		}

		userDN := sr.Entries[0].DN

		err = conn.Bind(userDN, password)
		if err != nil {
			return nil, errors.New("invalid credentials")
		}

		// query for the user's roles
		roleSearchRequest := ldap.NewSearchRequest(
			conf.LdapSettings.LdapSearchBaseDn,
			ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
			fmt.Sprintf("(&(objectClass=person)(sAMAccountName=%s))", ldap.EscapeFilter(username)),
			[]string{"memberOf"},
			nil,
		)

		sr, err = conn.Search(roleSearchRequest)
		if err != nil {
			return nil, err
		}

		hasAuthorizedRole := false
		for _, entry := range sr.Entries {
			for _, memberOf := range entry.GetAttributeValues("memberOf") {
				if memberOf == conf.LdapSettings.LdapAdminGroupDn ||
					memberOf == conf.LdapSettings.LdapRedGroupDn ||
					memberOf == conf.LdapSettings.LdapTeamGroupDn {
					hasAuthorizedRole = true
					break
				}

				if memberOf == conf.LdapSettings.LdapInjectGroupDn {
					return map[string]any{"username": username, "authSource": "ldap"}, nil
				}
			}
			if hasAuthorizedRole {
				break
			}
		}

		if !hasAuthorizedRole {
			return nil, errors.New("LDAP user has no authorized roles")
		}

		return map[string]any{"username": username, "authSource": "ldap"}, nil
	}

	return nil, errors.New("no auth source matched credentials")
}
